name: Build and release Go Project

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build project
        run: CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}
               go build
               -o vm-profile-setup-${{ matrix.goos }}-${{ matrix.goarch }}
               cmd/main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vm-profile-setup-linux-amd64
            vm-profile-setup-linux-arm64
            vm-profile-setup-windows-amd64
            vm-profile-setup-windows-arm64
            vm-profile-setup-darwin-amd64
            vm-profile-setup-darwin-arm64
