name: Build and release Go Project

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build project
        run: make # or 'go build .' etc...

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/praktikum-profile-setup
